### ISSUE TITLE
Occultist in classdb

### ISSUE THREAD

**Issue by baerrach** [baerrach/myth-weaver-utils-google-sheets#74]

**Comment by baerrach** [comment]
Thanks allefgib for doing most of the class features.
Implements are still to be done, they are massive.

**Comment by allefgib** [comment]
Can you add an ability to parse multiple values from the DC/spells known etc data fields?

e.g. assuming wizard/cleric spells avaialle maybe do

Spells known: 3/4
DC: 14/15

etc.
